
resources:
  repositories:
    - repository: 'anukritigupta1234/test'
      type: github
      endpoint: github2
      

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

