
resources:
  repositories:
    - repository: MyRepo
      type: github
      endpoint: github_1
      name: anukritigupta1234/test
      

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: MyRepo

